language: rust
rust: nightly

branches:
  only:
  - master

cache: cargo

addons:
  apt:
    packages:
    - python

script:
  # Copy testing env file if one exists
  - if [[ -f .env.testing ]]; then cp .env.testing .env; fi

  # Build
  - cargo build --verbose

  # Test
  - cargo test --verbose

