dist: trusty
sudo: required
language: rust
rust: nightly

branches:
  only:
  - master

cache: cargo

addons:
  apt:
    packages:
    - python3
    - python3-pip

install:
  - python --version
  - pip3 install --upgrade pip3
  - pip3 install tensorflow

script:
  # Copy testing env file if one exists
  - if [[ -f .env.testing ]]; then cp .env.testing .env; fi

  # Build
  - cargo build --verbose

  # Test
  - cargo test --verbose

